### ISSUE TITLE
Add a License

### ISSUE THREAD

**Issue by menixator** [thefloweringash/nixos-nftables#1]
Hi. I've forked this repository and was wondering if I could convince you to license the code so I could follow suit/dual license it.

Thanks.

**Comment by thefloweringash** [comment]
Hi. Sorry for the long silence. I always intended to upstream this to nixpkgs but ran out of enthusiasm due before doing so. The code is based partially on the existing module for nixpkgs (the interface, at least), which is MIT. Anything original in this repo should also be considered to have the same MIT license.

**Comment by menixator** [comment]
Alright thanks 👍
